### ISSUE TITLE
breaks eval-defun on 0.12.0

### ISSUE THREAD

**Issue by priyatam** [clojure-emacs/cider-eval-sexp-fu#4]
After upgrading to cider 0.12.0, this aspect breaks cider-debug feature with the following error:

```
ebugger entered--Lisp error: (void-function cider--region-for-defun-at-point)
  cider--region-for-defun-at-point()
  ad-Advice-cider-eval-defun-at-point((closure (t) (&optional debug-it) "Evaluate the current toplevel form, and print result in the minibuffer.\nWith DEBUG-IT prefix argument, also debug the entire form as with the\ncommand `cider-debug-defun-at-point'."
```

Here's the [line](https://github.com/clojure-emacs/cider/blob/master/cider-interaction.el#L1162) that it wraps. Cider debug works after disabling this package. 

thanks, @Malabarba for pointing this out on slack.

**Comment by Malabarba** [comment]
@bbatsov could you give me write access to this repo?

**Comment by bbatsov** [comment]
I did one better - you're now a co-owner of the organisation. :-) You've got the power now! :-)

**Comment by bbatsov** [comment]
@Malabarba ping :-)

**Comment by Malabarba** [comment]
Hm, I finally cloned the repo today. But it looks like this is already fixed. 
Maybe one of us fixed and forgot about it?

**Comment by Malabarba** [comment]
Here it is: 63b849b8f996032f662364c451c8e950ce94c8d9
